"""Argent Development Team — Phase 1: Deterministic Team-Control Core.

A fail-closed, deterministic team-control core implementing SPEC V1 + V1.1:
state machine, roles, gated autonomy, trust boundary, SQLite persistence,
privacy-safe events, idempotency and crash recovery.
"""

from .core import ActionRequestResult, Core, ReceiveResult, RecoveryReport
from .gates import EXTERNAL_ACTIONS, classify_action
from .models import (
    ActionClass,
    ActionExecution,
    ActionExecutionStatus,
    AgentContextSnapshot,
    AgentDispatch,
    AgentResultQuarantine,
    ApprovalError,
    ApprovalStatus,
    ArgentError,
    ArtifactCategory,
    Decision,
    DispatchError,
    DispatchStatus,
    Event,
    ExternalActionsPolicy,
    Finding,
    FindingStatus,
    ForbiddenAction,
    Handoff,
    IdempotencyError,
    InvalidTransition,
    NotFound,
    OutputValidationError,
    OwnerApproval,
    OwnerAuthorityRequired,
    Permission,
    PermissionDenied,
    PrivacyViolation,
    Project,
    Review,
    RiskClass,
    Role,
    RoleConflict,
    RolePolicyViolation,
    RoleRun,
    RoleRunStatus,
    SequenceKind,
    SourceClass,
    Task,
    TaskRun,
    TaskRunStatus,
    TaskState,
    TestResult,
    TestRun,
    UntrustedSource,
)
from .roles import DEFAULT_NEXT_ROLE, can_read, can_write, check_permission
from .routing import resolve_model, validate_model_choice
from .state_machine import is_allowed, is_valid_resume_target, validate_transition
from .store import Queries
from .trust import OWNER_SOURCE, classify_source, role_source

__all__ = [
    "ActionClass",
    "ActionExecution",
    "ActionExecutionStatus",
    "ActionRequestResult",
    "AgentContextSnapshot",
    "AgentDispatch",
    "AgentResultQuarantine",
    "ApprovalError",
    "ApprovalStatus",
    "ArgentError",
    "ArtifactCategory",
    "Core",
    "DEFAULT_NEXT_ROLE",
    "Decision",
    "DispatchError",
    "DispatchStatus",
    "Event",
    "EXTERNAL_ACTIONS",
    "ExternalActionsPolicy",
    "Finding",
    "FindingStatus",
    "ForbiddenAction",
    "Handoff",
    "IdempotencyError",
    "InvalidTransition",
    "NotFound",
    "OWNER_SOURCE",
    "OutputValidationError",
    "OwnerApproval",
    "OwnerAuthorityRequired",
    "Permission",
    "PermissionDenied",
    "PrivacyViolation",
    "Project",
    "Queries",
    "ReceiveResult",
    "RecoveryReport",
    "Review",
    "RiskClass",
    "Role",
    "RoleConflict",
    "RolePolicyViolation",
    "RoleRun",
    "RoleRunStatus",
    "SequenceKind",
    "SourceClass",
    "Task",
    "TaskRun",
    "TaskRunStatus",
    "TaskState",
    "TestResult",
    "TestRun",
    "UntrustedSource",
    "can_read",
    "can_write",
    "check_permission",
    "classify_action",
    "classify_source",
    "is_allowed",
    "is_valid_resume_target",
    "resolve_model",
    "role_source",
    "validate_model_choice",
    "validate_transition",
]
